version: '3.8'
services:
  app:
    build: ./docker/php-fpm
    environment:
      - MYSQL_HOST=db
    depends_on:
      - db
    volumes:
      - ${APP_BASE_DIR}/webapp:/app:cached
      - ./docker/php-fpm/tmp:/tmp:delegated
      - ./docker/php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
    working_dir: /app
  web:
    image: nginx:alpine
    ports:
      - ${WEB_HTTP_PORT:-80}:80
    depends_on:
      - app
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
  db:
    image: mysql:${DB_MYSQL_VERSION:-8.0}
    environment:
      - MYSQL_DATABASE=${DB_DATABASE:-db}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-password}
    ports:
      - ${DB_PORT:-3306}:3306
    volumes:
      - db-volume:/var/lib/mysql
      - ./docker/mysql/logs:/var/log/mysql:delegated
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
  bench-build:
    image: golang:1.15
    volumes:
      - ${APP_BASE_DIR}:/app
    working_dir: /app
    command: make clean all
  bench:
    image: golang:1.15
    volumes:
      - ${APP_BASE_DIR}:/app
    working_dir: /app
    command: /app/bin/benchmarker -payment-url http://bench:5555 -shipment-url http://bench:7000 -target-url http://app:8000

volumes:
  db-volume:
