version: '3.8'
services:
  app:
    image: php:7.4-fpm-alpine
    depends_on:
      - db
    volumes:
      - ./src:/app:cached
      - ./docker/php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
    working_dir: /app
  web:
    image: nginx:alpine
    ports:
      - ${WEB_HTTP_PORT:-80}:80
    depends_on:
      - app
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/site.conf:/etc/nginx/site.conf
  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=${DB_DATABASE:-db}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-password}
    ports:
      - ${DB_PORT:-3306}:3306
    volumes:
      - db-volume:/var/lib/mysql
      - ./docker/mysql/logs:/var/log/mysql:delegated
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro

volumes:
  db-volume:
